DessertApp/Controllers/DessertsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DessertApp.Models;
using PagedList;

namespace DessertApp.Controllers
{
    public class DessertsController : Controller
    {
        private DessertDb db = new DessertDb();

        //implement pagination


        // GET: Desserts
        public ActionResult Index(string sortOrder, string currentFilter, string search, int? page)
        {
            ViewBag.CurrentSort = sortOrder;

            ViewBag.TitleSortParm = String.IsNullOrEmpty(sortOrder) ? "title_desc" : "";
            ViewBag.DietarySortParm = sortOrder == "Dietary" ? "diet_desc" : "Dietary";


            if (search != null)
            {
                page = 1;
            }
            else
            {
                search = currentFilter;
            }

            ViewBag.CurrentFilter = search;


            var desserts = from s in db.Desserts
                           select s;

            if (!String.IsNullOrEmpty(search))
            {
                desserts = desserts.Where(s => s.Title.Contains(search)
                                       || s.Dietary.Contains(search)
                                       );
            }

            switch (sortOrder)
            {
                case "title_desc":
                    desserts = desserts.OrderByDescending(s => s.Title);
                    break;
                case "Dietary":
                    desserts = desserts.OrderBy(s => s.Dietary);
                    break;
                case "diet_desc":
                    desserts = desserts.OrderByDescending(s => s.Dietary);
                    break;
                default:
                    desserts = desserts.OrderBy(s => s.Title);
                    break;
            }


            int pageSize = 3;
            int pageNumber = (page ?? 1);
            return View(desserts.ToPagedList(pageNumber, pageSize));

            //  return View(db.Desserts.ToList());
        }

        public ActionResult Like(int id)

        {
            Dessert dessert = db.Desserts.Find(id);

            int currentLikes = dessert.Like;

            dessert.Like = currentLikes + 1;

            if (ModelState.IsValid)

            {

                db.Entry(dessert).State = EntityState.Modified;
                db.SaveChanges();

            }

            return RedirectToAction("Index");

        }

        public ActionResult Dislike(int id)

        {

            Dessert dessert = db.Desserts.Find(id);

            int currentDislikes = dessert.Dislikes;

            dessert.Dislikes = currentDislikes + 1;

            if (ModelState.IsValid)

            {

                db.Entry(dessert).State = EntityState.Modified;
                db.SaveChanges();

            }

            return RedirectToAction("Index");

        }


        // GET: Desserts/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dessert dessert = db.Desserts.Find(id);
            if (dessert == null)
            {
                return HttpNotFound();
            }
            return View(dessert);
        }

        // GET: Desserts/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Desserts/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Title,Dietary,Ingredients,CookTime,PrepTime,RecipeMethod,Servings,DessertArtUrl,Like,Dislikes,User")] Dessert dessert)
        {
            if (ModelState.IsValid)
            {
                db.Desserts.Add(dessert);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dessert);
        }

        // GET: Desserts/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dessert dessert = db.Desserts.Find(id);
            if (dessert == null)
            {
                return HttpNotFound();
            }
            return View(dessert);
        }

        // POST: Desserts/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Title,Dietary,Ingredients,CookTime,PrepTime,RecipeMethod,Servings,DessertArtUrl,Like,Dislikes,User")] Dessert dessert)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dessert).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dessert);
        }

        // GET: Desserts/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Dessert dessert = db.Desserts.Find(id);
            if (dessert == null)
            {
                return HttpNotFound();
            }
            return View(dessert);
        }

        // POST: Desserts/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Dessert dessert = db.Desserts.Find(id);
            db.Desserts.Remove(dessert);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

DessertApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using DessertApp.Models;


namespace DessertApp.Controllers
{
    public class HomeController : Controller
    {

        private DessertDb db = new DessertDb();


        public ActionResult Index()
        {
            return View(db.Desserts.ToList());

            //Get all desserts
            //my model image url ==@model.url---in view and url.action to find/take you to recipe of image


        }


        public ActionResult TopRated()
        {
            var dessert = GetTopRated();

            return PartialView("_TopRated", dessert);
        }


        private Dessert GetTopRated()

        {
            var dessert = db.Desserts
                .OrderByDescending(a => a.Like)
                .First();
                
            return dessert;
           

        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

DessertApp/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

DessertApp/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DessertApp/Views/Home/Index.cshtml
@model IEnumerable<DessertApp.Models.Dessert>

@{
    ViewBag.Title = "Ever So Sweet Desserts";
}

<div class="homeheading">
    <h1>Ever So Sweet Desserts</h1>
</div>


  <h5><b>  @Html.ActionLink("Explore Delicious Dessert Recipes", "Index", "Desserts") </b></h5>

<br />

<div id="myCarousel" class="carousel slide " style="width:450px; height: auto; margin:0 auto; border:ridge 6px darkred; " data-ride="carousel">

    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
        <li data-target="#myCarousel" data-slide-to="3"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner" role="listbox">
        @{int i = 0;}
        @foreach (var item in Model)
        {
            {
                i++;
                var active = i == 1 ? "active" : "";
                <div class="item @active">

                    <a href="@Url.Action("Details", "Desserts", new { Id = item.Id })">
                        <img src="@Url.Content(item.DessertArtUrl)" alt="Dessert">

                    </a>

                </div>


            }
        }
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<br />

@section Scripts {
    
<script src="~/Scripts/jquery.unobtrusive-ajax.min.js"></script>

    }


<div id="toprated">
    @Ajax.ActionLink("View Top Rated Dessert",
    "TopRated",
    null,
    new AjaxOptions
    { UpdateTargetId = "toprated",
        InsertionMode = InsertionMode.Replace,
        HttpMethod = "GET"
    },

    new { @class = "btn btn-primary"})

</div>

DessertApp/Views/Home/_TopRated.cshtml
@model DessertApp.Models.Dessert






<div class="panel-primary col-sm-11" style="margin-left:135px; margin-right:130px">

    <div class="panel-heading col-sm-8">
        <h3 class="panel-title">Top Rated Dessert: @Model.Title</h3>
    </div>
    <div class="panel-body col-sm-8">
        <p class="img-topRated col-sm-6" style="padding-right: 0px; padding-left:0px; padding-top:0px;">

            <br />

            
                <img alt="@Model.Title"
                     src="@Url.Content(@Model.DessertArtUrl)" width="170" height="170" class="img-rounded"
                      style="margin:0px auto;  border:3px solid darkred" />
            </p>

        <br />

        <div id="dessert-details col-sm-3">
            <p>
                <b>Likes:</b>
                @Model.Like
            </p>
            <p>
            <b>Recipe By:</b>
             @Model.User</p>

            @Html.ActionLink("View Recipe","Details", "Desserts", new { id = Model.Id }, new { @class = "btn btn-default btn-md" })
            
            
           
           
        </div>
    </div>
</div>

<br />